#!/bin/zsh

# Frequently updated
./rc /Volumes/GALILEO/Documentos One:Documentos
./rc /Volumes/GALILEO/Estudios One:Estudios
./rc --sync /Volumes/GALILEO/Programacion One:Programacion

# Not as frequent
./rc /Volumes/GALILEO/Historias One:Historias
./rc /Volumes/GALILEO/Proyectos One:Proyectos

# Slower, they go at the end since they can stop everything else from syncing
./rc /Volumes/GALILEO/Videos One:Videos
./rc /Volumes/GALILEO/Fotos One:Fotos
